### PR TITLE
Space Travelers Hub - React App

### PR DESCRIPTION
**Pull request by alonsofl**
### Summary
Web application for a company that provides commercial and scientific space travel services. The application will allow users to book rockets and join selected space missions.

#### Details
- Created React components for Header, Rockets, Missions, and My Profile.
- Added React Router to the application.
- Connected React and Redux.
- Created Redux store, actions, and reducers for Rockets and Missions.
- Fetch data from the SpaceX API and stored it with the requested structure.
- Added event handlers for rocket reservation and mission joining.
- Added conditional components for rockets and missions reserved.
- Added required style for the components.
- Added tests for the application.

> [Video presentation](https://www.loom.com/share/4e876f7436be4acea2327b129826aac4)

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
### Hi Team 🙋‍♀️, 

Overall great project! 👌 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

#  Required Changes ♻️ 🚧

image

- [ ] Kindly fix this failing test


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alonsofl** [comment]
Hello @AshakaE,

Thanks for your time! About the issue, I have tried several times and I have no errors. Also, I asked a partner to try on his computer, and he doesn't get errors either.

image

**Comment by alonsofl** [comment]
Thanks, @mricanho and @AshakaE!

**Comment by Temmarie** [comment]
Hello 👋,

This is an additional review as a result of the second opinion request.

Looks like the issue was resolved here, so I have nothing else to say other than best of luck with the rest of your projects!

Keep rocking 🚀!

**Pull request merged**
